version: '3'

#Docker Networks
networks:
  default:
    driver: bridge

services:
  #PHP-fpm + nginx Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    working_dir: /var/www



  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db-rbc
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rbc
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - default


